/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package help4travelling;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Agustin
 */
public class ActualizarServicio extends javax.swing.JFrame {
    private IControladorArticulo ICArticulo;
    private IControladorCategoria ICCategoria;
    DefaultListModel<String> list2 = new DefaultListModel<>();
    DefaultListModel<String> list3 = new DefaultListModel<>();
    File fileServicio1;
    File fileServicio2;
    File fileServicio3;
    /**
     * Creates new form AltaUsuario
     */
    public ActualizarServicio() {
        initComponents();
        ICArticulo = Factory.GetInstance().getIControladorArticulo();
        ICCategoria = Factory.GetInstance().getIControladorCategoria();
    }
    
    private Image ScaledImage(Image img, int w, int h){
        BufferedImage resizedImage = new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = resizedImage.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(img, 0, 0, w, h,null);
        g2.dispose();
        return resizedImage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        cmb_destino = new javax.swing.JComboBox<>();
        jLabel130 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_desc = new javax.swing.JTextPane();
        jLabel131 = new javax.swing.JLabel();
        jLabel199 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        cmb_actualizar_servicio = new javax.swing.JComboBox<>();
        cmb_origen = new javax.swing.JComboBox<>();
        jLabel135 = new javax.swing.JLabel();
        txt_p = new javax.swing.JTextField();
        jLabel203 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel218 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        list_catServicio = new javax.swing.JList<>();
        btn_addP1 = new javax.swing.JLabel();
        btn_rmP1 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel206 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        tree_actualizar_servicios = new javax.swing.JTree();
        jLabel42 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setBounds(new java.awt.Rectangle(0, 0, 1218, 707));
        setMaximumSize(new java.awt.Dimension(1218, 707));
        setMinimumSize(new java.awt.Dimension(1218, 707));
        setPreferredSize(new java.awt.Dimension(1218, 707));
        setResizable(false);
        setSize(new java.awt.Dimension(1218, 707));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1220, 10));

        jLabel122.setBackground(java.awt.Color.darkGray);
        jLabel122.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel122.setForeground(java.awt.Color.darkGray);
        jLabel122.setText("Ciudad Destino");
        getContentPane().add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel127.setBackground(java.awt.Color.darkGray);
        jLabel127.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel127.setForeground(java.awt.Color.darkGray);
        jLabel127.setText("Precio");
        getContentPane().add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel128.setBackground(java.awt.Color.darkGray);
        jLabel128.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel128.setForeground(java.awt.Color.darkGray);
        jLabel128.setText("Imagenes");
        getContentPane().add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/confirmar.png"))); // NOI18N
        jLabel77.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel77.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel77.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel77.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel77.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel77MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 630, 43, 43));

        cmb_destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmb_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 300, -1));

        jLabel130.setBackground(java.awt.Color.darkGray);
        jLabel130.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel130.setForeground(java.awt.Color.darkGray);
        jLabel130.setText("Ciudad Origen");
        getContentPane().add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 20));

        jScrollPane2.setViewportView(txt_desc);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 540, 120));

        jLabel131.setBackground(java.awt.Color.darkGray);
        jLabel131.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel131.setForeground(java.awt.Color.darkGray);
        jLabel131.setText("Servicio");
        getContentPane().add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        jLabel199.setBackground(java.awt.Color.white);
        jLabel199.setOpaque(true);
        getContentPane().add(jLabel199, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 210, 140));

        jButton12.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        jButton12.setText("Imagen 3");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, -1, -1));

        cmb_actualizar_servicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_actualizar_servicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_actualizar_servicioItemStateChanged(evt);
            }
        });
        getContentPane().add(cmb_actualizar_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 310, -1));

        cmb_origen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmb_origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 300, -1));

        jLabel135.setBackground(java.awt.Color.darkGray);
        jLabel135.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel135.setForeground(java.awt.Color.darkGray);
        jLabel135.setText("Descripcion");
        getContentPane().add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        txt_p.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        getContentPane().add(txt_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 150, -1));

        jLabel203.setBackground(java.awt.Color.white);
        jLabel203.setOpaque(true);
        getContentPane().add(jLabel203, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 220, 140));

        jButton14.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        jButton14.setText("Imagen 1");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel218.setBackground(java.awt.Color.white);
        jLabel218.setOpaque(true);
        getContentPane().add(jLabel218, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 220, 140));

        jButton15.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        jButton15.setText("Imagen 2");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        jScrollPane10.setViewportView(list_catServicio);

        getContentPane().add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 150, 220, 440));

        btn_addP1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_addP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/next.png"))); // NOI18N
        btn_addP1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_addP1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_addP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addP1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addP1MouseEntered(evt);
            }
        });
        getContentPane().add(btn_addP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 36, 36));

        btn_rmP1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_rmP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/back.png"))); // NOI18N
        btn_rmP1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_rmP1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_rmP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_rmP1MouseClicked(evt);
            }
        });
        getContentPane().add(btn_rmP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 370, 36, 36));

        jLabel117.setBackground(java.awt.Color.darkGray);
        jLabel117.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel117.setForeground(java.awt.Color.darkGray);
        jLabel117.setText("CATEGORIAS DEL SERVICIO");
        getContentPane().add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 120, -1, -1));

        jLabel206.setBackground(java.awt.Color.darkGray);
        jLabel206.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel206.setForeground(java.awt.Color.darkGray);
        jLabel206.setText("CATEGORIAS DISPONIBLES");
        getContentPane().add(jLabel206, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, -1, -1));

        jButton16.setBackground(java.awt.Color.white);
        jButton16.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jButton16.setText("Limpiar");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 590, -1, -1));

        tree_actualizar_servicios.setAutoscrolls(true);
        tree_actualizar_servicios.addTreeExpansionListener(new javax.swing.event.TreeExpansionListener() {
            public void treeCollapsed(javax.swing.event.TreeExpansionEvent evt) {
            }
            public void treeExpanded(javax.swing.event.TreeExpansionEvent evt) {
                tree_actualizar_serviciosTreeExpanded(evt);
            }
        });
        tree_actualizar_servicios.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                tree_actualizar_serviciosValueChanged(evt);
            }
        });
        jScrollPane14.setViewportView(tree_actualizar_servicios);

        getContentPane().add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 220, 470));

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/error.png"))); // NOI18N
        jLabel42.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 630, 42, 42));

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setEnabled(false);
        jLabel1.setFocusable(false);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1218, 600));

        jLabel3.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Actualización de servicio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/banner2.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel77MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel77MouseClicked
        if((!txt_desc.getText().isEmpty()) && (!txt_desc.getText().isEmpty()) && (list_catServicio.getModel().getSize() != 0) ){
            String nickP, nombreA;
            nickP = cmb_actualizar_servicio.getSelectedItem().toString().substring(0, cmb_actualizar_servicio.getSelectedItem().toString().lastIndexOf(","));
            nombreA = cmb_actualizar_servicio.getSelectedItem().toString().substring(cmb_actualizar_servicio.getSelectedItem().toString().lastIndexOf(",")+2);

            ArrayList<String> categorias = new ArrayList();

            ListModel lm = list_catServicio.getModel();
            for(int e = 0; e < list_catServicio.getModel().getSize(); e++){
                //System.out.println(list_catServicio.getModel().getElementAt(e));
                categorias.add(list_catServicio.getModel().getElementAt(e));
            }

            DtServicio mod = new DtServicio(nombreA.trim(), nickP.trim(), Float.valueOf(txt_p.getText().trim()), txt_desc.getText(), categorias, cmb_origen.getSelectedItem().toString().trim(), cmb_destino.getSelectedItem().toString().trim());
            ICArticulo.ModificarServicio(mod);
            if(jLabel203.getIcon() != null){
                try {
                    ManejadorSQL.GetInstance().insertImgServicio(fileServicio1, "imagen1", nickP.trim(), nombreA.trim());
                }
                catch (FileNotFoundException ex) {

                }
            }
            if(jLabel218.getIcon() != null){
                try {
                    ManejadorSQL.GetInstance().insertImgServicio(fileServicio2, "imagen2", nickP.trim(), nombreA.trim());
                }
                catch (FileNotFoundException ex) {

                }
            }
            if(jLabel199.getIcon() != null){
                try {
                    ManejadorSQL.GetInstance().insertImgServicio(fileServicio1, "imagen3", nickP.trim(), nombreA.trim());
                }
                catch (FileNotFoundException ex) {

                }
            }
            JOptionPane.showMessageDialog(null, "Servicio actualizado correctamente!");
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Error!. Compruebe que los campos mínimos requeridos no esten vacíos.");
        }
    }//GEN-LAST:event_jLabel77MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        fileServicio3 = null;
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        fileServicio3 = fc.getSelectedFile();
        String ruta = fileServicio3.getAbsolutePath();
        Rectangle t = jLabel199.getBounds();
        jLabel199.setIcon(new ImageIcon(ruta));
        jLabel199.setBounds(t);  
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void cmb_actualizar_servicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_actualizar_servicioItemStateChanged
        String nickP, nombreA;
        list3.clear();
        if(cmb_actualizar_servicio.getModel().getSize() != 0){
            if(!cmb_actualizar_servicio.getSelectedItem().toString().trim().isEmpty()){
                nickP = cmb_actualizar_servicio.getSelectedItem().toString().substring(0, cmb_actualizar_servicio.getSelectedItem().toString().lastIndexOf(","));
                nombreA = cmb_actualizar_servicio.getSelectedItem().toString().substring(cmb_actualizar_servicio.getSelectedItem().toString().lastIndexOf(",")+1);
                DtServicio ret = ICArticulo.datosServicio(nombreA.trim(), nickP.trim());
                //System.out.println(ret.getCiudadOrigen());
                //System.out.println(ret.getCiudadDestino());
                if(cmb_origen.getModel().getSize() != 0){
                    for(int x = 0; x < cmb_origen.getModel().getSize(); x++){
                        if(cmb_origen.getModel().getElementAt(x).trim().equals(ret.getCiudadOrigen().trim())){
                            cmb_origen.setSelectedItem(ret.getCiudadOrigen().trim());
                        }
                    }
                }
                if(cmb_destino.getModel().getSize() != 0){
                    for(int x = 0; x < cmb_destino.getModel().getSize(); x++){
                        if(ret.getCiudadDestino() != null ){
                            if(cmb_destino.getModel().getElementAt(x).trim().equals(ret.getCiudadDestino().trim())){
                                cmb_destino.setSelectedItem(ret.getCiudadDestino());
                            }
                        }
                    }
                }
                txt_desc.setText(ret.getDescripcion());
                txt_p.setText(""+ret.getPrecio());
                for(int x = 0; x < ret.getCategorias().size(); x++){
                    list3.addElement(ret.getCategorias().get(x).trim());
                }
                
                jLabel203.setIcon(null);
                if(ManejadorSQL.GetInstance().selectImgServicio("imagen1", nickP, nombreA) != null){
                    Image a =  new ImageIcon(ManejadorSQL.GetInstance().selectImgServicio("imagen1", nickP, nombreA)).getImage();
                    ImageIcon icon = new ImageIcon(ScaledImage(a,jLabel203.getWidth(),jLabel203.getHeight()));
                    jLabel203.setIcon(icon);
                }

                jLabel218.setIcon(null);
                if(ManejadorSQL.GetInstance().selectImgServicio("imagen2", nickP, nombreA) != null){
                    Image a =  new ImageIcon(ManejadorSQL.GetInstance().selectImgServicio("imagen2", nickP, nombreA)).getImage();
                    ImageIcon icon = new ImageIcon(ScaledImage(a,jLabel218.getWidth(),jLabel218.getHeight()));
                    jLabel218.setIcon(icon);
                }

                jLabel199.setIcon(null);
                if(ManejadorSQL.GetInstance().selectImgServicio("imagen3", nickP, nombreA) != null){
                    Image a =  new ImageIcon(ManejadorSQL.GetInstance().selectImgServicio("imagen3", nickP, nombreA)).getImage();
                    ImageIcon icon = new ImageIcon(ScaledImage(a,jLabel199.getWidth(),jLabel199.getHeight()));
                    jLabel199.setIcon(icon);
                }
            }
        }
        list_catServicio.setModel(list3);
    }//GEN-LAST:event_cmb_actualizar_servicioItemStateChanged

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        fileServicio1 = null;
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        fileServicio1 = fc.getSelectedFile();
        String ruta = fileServicio1.getAbsolutePath();
        Rectangle t = jLabel203.getBounds();
        jLabel203.setIcon(new ImageIcon(ruta));
        jLabel203.setBounds(t);
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        fileServicio2 = null;
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        fileServicio2 = fc.getSelectedFile();
        String ruta = fileServicio2.getAbsolutePath();
        Rectangle t = jLabel218.getBounds();
        jLabel218.setIcon(new ImageIcon(ruta));
        jLabel218.setBounds(t);  
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void btn_addP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addP1MouseClicked
        if((DefaultMutableTreeNode)tree_actualizar_servicios.getLastSelectedPathComponent() != null){
            DefaultMutableTreeNode node = (DefaultMutableTreeNode)tree_actualizar_servicios.getLastSelectedPathComponent();
            String nameCat = node.getUserObject().toString().trim();
            if(!list3.contains(nameCat))
                list3.addElement(nameCat);
            list_catServicio.setModel(list3);
        }
    }//GEN-LAST:event_btn_addP1MouseClicked

    private void btn_addP1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addP1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addP1MouseEntered

    private void btn_rmP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rmP1MouseClicked
        if(list_catServicio.getSelectedValue() != null){
            ((DefaultListModel)list_catServicio.getModel()).removeElementAt(list_catServicio.getSelectedIndex());
        }
    }//GEN-LAST:event_btn_rmP1MouseClicked

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        if(list_catServicio.getModel().getSize() != 0)
            ((DefaultListModel)list_catServicio.getModel()).removeAllElements();
    }//GEN-LAST:event_jButton16MouseClicked

    private void tree_actualizar_serviciosTreeExpanded(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_tree_actualizar_serviciosTreeExpanded
        // TODO add your handling code here:
    }//GEN-LAST:event_tree_actualizar_serviciosTreeExpanded

    private void tree_actualizar_serviciosValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_tree_actualizar_serviciosValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tree_actualizar_serviciosValueChanged

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel42MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        List<String> c = ICArticulo.listaDeCiudades();  ArrayList<DtServicio> s = ICArticulo.ListarServicios(); DefaultComboBoxModel lm = new DefaultComboBoxModel(); DefaultComboBoxModel lm2 = new DefaultComboBoxModel(), lm3 = new DefaultComboBoxModel();
        for(int x = 0; x < s.size(); x++){
            lm.addElement(s.get(x).getNickProveedor() + ", " + s.get(x).getNombre());
        }
        cmb_actualizar_servicio.setModel(lm);
        for(int e = 0; e < c.size(); e++){
            lm2.addElement(c.get(e));
            lm3.addElement(c.get(e));
        }
        cmb_origen.setModel(lm2);
        cmb_destino.setModel(lm3);
        DefaultMutableTreeNode tree = new DefaultMutableTreeNode("todas");
        ArrayList<DtCategoria> categorias = ICCategoria.listarCategorias();

        int max =0;
        for (int i = 0; i < categorias.size(); i++){
            if (max < categorias.get(i).getNivel()){
                max =categorias.get(i).getNivel();
            }
        }
        HashMap<String, DefaultMutableTreeNode> tree2 = new HashMap();
        tree2.put("todas", tree);
        for (int j = 0; j < max+1; j++){
            for (DtCategoria categoria : categorias) {
                if(j == categoria.getNivel()){
                    DefaultMutableTreeNode cat = new DefaultMutableTreeNode();
                    cat.setUserObject(categoria.getNombre());
                    for(String name : tree2.keySet()){
                        if(name.equals(categoria.getNombrePadre()))
                            tree2.get(name).add(cat);
                    }
                    //tree.add(cat);
                    tree2.put(categoria.getNombre(), cat);
                }
            }
        }
        DefaultTreeModel modeloTree = new DefaultTreeModel(tree);
        tree_actualizar_servicios.setModel(modeloTree);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_addP1;
    private javax.swing.JLabel btn_rmP1;
    private javax.swing.JComboBox<String> cmb_actualizar_servicio;
    private javax.swing.JComboBox<String> cmb_destino;
    private javax.swing.JComboBox<String> cmb_origen;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel199;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JLabel jLabel218;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> list_catServicio;
    private javax.swing.JTree tree_actualizar_servicios;
    private javax.swing.JTextPane txt_desc;
    private javax.swing.JTextField txt_p;
    // End of variables declaration//GEN-END:variables
}
