/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package help4travelling;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Agustin
 */
public class ConsultarCliente extends javax.swing.JFrame {
    DefaultListModel<String> list2 = new DefaultListModel<>();
    DefaultListModel<String> list3 = new DefaultListModel<>();
    private IControladorUsuario ICUsuario;
    private IControladorReserva ICReserva;
    /**
     * Creates new form AltaUsuario
     */
    public ConsultarCliente() {
        initComponents();
        ICUsuario = Factory.GetInstance().getIControladorUsuario();
        ICReserva = Factory.GetInstance().getIControladorReserva();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel186 = new javax.swing.JLabel();
        jLabel187 = new javax.swing.JLabel();
        jLabel188 = new javax.swing.JLabel();
        ListaCli = new javax.swing.JComboBox<>();
        jScrollPane13 = new javax.swing.JScrollPane();
        Articulo = new javax.swing.JList<>();
        jLabel214 = new javax.swing.JLabel();
        AnioCli = new javax.swing.JLabel();
        jLabel216 = new javax.swing.JLabel();
        jLabel217 = new javax.swing.JLabel();
        lbl_avatarCliente = new javax.swing.JLabel();
        jLabel222 = new javax.swing.JLabel();
        jLabel223 = new javax.swing.JLabel();
        jLabel224 = new javax.swing.JLabel();
        jScrollPane20 = new javax.swing.JScrollPane();
        ReservasCli = new javax.swing.JList<>();
        jLabel218 = new javax.swing.JLabel();
        EmailCli = new javax.swing.JLabel();
        ApeCli = new javax.swing.JLabel();
        DiaCli = new javax.swing.JLabel();
        MesCli = new javax.swing.JLabel();
        PrecioCli = new javax.swing.JLabel();
        NomCli = new javax.swing.JLabel();
        FCCli = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setEnabled(false);
        jLabel1.setFocusable(false);
        jLabel1.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setBounds(new java.awt.Rectangle(0, 0, 1218, 707));
        setMaximumSize(new java.awt.Dimension(1218, 707));
        setMinimumSize(new java.awt.Dimension(1218, 707));
        setPreferredSize(new java.awt.Dimension(1218, 707));
        setResizable(false);
        setSize(new java.awt.Dimension(1218, 707));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1220, 10));

        jLabel186.setBackground(java.awt.Color.darkGray);
        jLabel186.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel186.setForeground(java.awt.Color.darkGray);
        jLabel186.setText("Reservas del cliente");
        getContentPane().add(jLabel186, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel187.setBackground(java.awt.Color.darkGray);
        jLabel187.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel187.setForeground(java.awt.Color.darkGray);
        jLabel187.setText("Clientes");
        getContentPane().add(jLabel187, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel188.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/confirmar.png"))); // NOI18N
        jLabel188.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel188.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel188.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel188.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel188.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel188MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel188, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 630, 43, 43));

        ListaCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListaCli.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ListaCliItemStateChanged(evt);
            }
        });
        ListaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaCliActionPerformed(evt);
            }
        });
        getContentPane().add(ListaCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 260, -1));

        Articulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArticuloMouseClicked(evt);
            }
        });
        jScrollPane13.setViewportView(Articulo);

        getContentPane().add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 190, 260));

        jLabel214.setBackground(java.awt.Color.darkGray);
        jLabel214.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel214.setForeground(java.awt.Color.darkGray);
        jLabel214.setText("Fecha Nacimiento");
        getContentPane().add(jLabel214, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        AnioCli.setBackground(java.awt.Color.white);
        AnioCli.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        AnioCli.setOpaque(true);
        getContentPane().add(AnioCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 70, 20));

        jLabel216.setBackground(java.awt.Color.darkGray);
        jLabel216.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel216.setForeground(java.awt.Color.darkGray);
        jLabel216.setText("Apellido");
        getContentPane().add(jLabel216, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel217.setBackground(java.awt.Color.darkGray);
        jLabel217.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel217.setForeground(java.awt.Color.darkGray);
        jLabel217.setText("E-mail");
        getContentPane().add(jLabel217, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        lbl_avatarCliente.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        getContentPane().add(lbl_avatarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 510, 250));

        jLabel222.setBackground(java.awt.Color.darkGray);
        jLabel222.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel222.setForeground(java.awt.Color.darkGray);
        jLabel222.setText("Precio total");
        getContentPane().add(jLabel222, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, 20));

        jLabel223.setBackground(java.awt.Color.darkGray);
        jLabel223.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel223.setForeground(java.awt.Color.darkGray);
        jLabel223.setText("Fecha de Creacion");
        getContentPane().add(jLabel223, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, 20));

        jLabel224.setBackground(java.awt.Color.darkGray);
        jLabel224.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel224.setForeground(java.awt.Color.darkGray);
        jLabel224.setText("Servicios y promociones");
        getContentPane().add(jLabel224, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        jScrollPane20.setBackground(java.awt.Color.white);

        ReservasCli.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ReservasCli.setValueIsAdjusting(true);
        ReservasCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservasCliMouseClicked(evt);
            }
        });
        jScrollPane20.setViewportView(ReservasCli);

        getContentPane().add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 230, 350));

        jLabel218.setBackground(java.awt.Color.darkGray);
        jLabel218.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel218.setForeground(java.awt.Color.darkGray);
        jLabel218.setText("Nombre");
        getContentPane().add(jLabel218, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        EmailCli.setBackground(java.awt.Color.white);
        EmailCli.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        EmailCli.setOpaque(true);
        getContentPane().add(EmailCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 260, 20));

        ApeCli.setBackground(java.awt.Color.white);
        ApeCli.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        ApeCli.setOpaque(true);
        getContentPane().add(ApeCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 260, 20));

        DiaCli.setBackground(java.awt.Color.white);
        DiaCli.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        DiaCli.setOpaque(true);
        getContentPane().add(DiaCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 70, 20));

        MesCli.setBackground(java.awt.Color.white);
        MesCli.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        MesCli.setOpaque(true);
        getContentPane().add(MesCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 70, 20));

        PrecioCli.setBackground(java.awt.Color.white);
        PrecioCli.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        PrecioCli.setOpaque(true);
        getContentPane().add(PrecioCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 140, 20));

        NomCli.setBackground(java.awt.Color.white);
        NomCli.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        NomCli.setOpaque(true);
        getContentPane().add(NomCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 260, 20));

        FCCli.setBackground(java.awt.Color.white);
        FCCli.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        FCCli.setOpaque(true);
        getContentPane().add(FCCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 170, 20));

        jLabel3.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Ver información de cliente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/banner2.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, -1));

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setEnabled(false);
        jLabel4.setFocusable(false);
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1218, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel188MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel188MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel188MouseClicked

    private void ListaCliItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ListaCliItemStateChanged

        NomCli.setVisible(true);
        ApeCli.setVisible(true);
        AnioCli.setVisible(true);
        MesCli.setVisible(true);
        DiaCli.setVisible(true);
        EmailCli.setVisible(true);
        FCCli.setVisible(true);
        PrecioCli.setVisible(true);

        list2.clear();

        NomCli.setText("");
        ApeCli.setText("");
        AnioCli.setText("");
        MesCli.setText("");
        DiaCli.setText("");
        EmailCli.setText("");
        FCCli.setText("");
        PrecioCli.setText("");

        String clie = ListaCli.getSelectedItem().toString();
        DtCliente DtCli = ICUsuario.datosCliente(clie);

        lbl_avatarCliente.setIcon(null);
        if(ManejadorSQL.GetInstance().selectImgUsuario(DtCli.getNick().trim()) != null){
            Image a =  new ImageIcon(ManejadorSQL.GetInstance().selectImgUsuario(DtCli.getNick().trim())).getImage();
            ImageIcon icon = new ImageIcon(a);
            lbl_avatarCliente.setIcon(icon);
        }

        NomCli.setText(DtCli.getNombre());
        ApeCli.setText(DtCli.getApellido());
        AnioCli.setText(Integer.toString(DtCli.getFechaN().getAnio()));
        MesCli.setText(Integer.toString(DtCli.getFechaN().getMes()));
        DiaCli.setText(Integer.toString(DtCli.getFechaN().getDia()));
        EmailCli.setText(DtCli.getEmail());
        //FCCli.setText(DtCli.);
        //PrecioCli.setText();

        //txt_DescripcionP.setText(DtProv.)
        // java.util.List<DtServicio> listdtServ = new ArrayList();
        //listdtServ = Dtcli.getServicio();
        java.util.List<Integer> listnrores = new ArrayList();
        listnrores= DtCli.getReservas();

        //java.util.List<String> lista = new ArrayList();

        //listnrores.forEach(i -> lista.add(((DtServicio)i).getNombre()));

        //if(!list2.contains(jList_ServiciosP.getSelectedValue())){
            listnrores.forEach(i -> list2.addElement(Integer.toString(i)));
            //}
        ReservasCli.setModel(list2);
        list3.clear();
        Articulo.setModel(list3);
    }//GEN-LAST:event_ListaCliItemStateChanged

    private void ArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArticuloMouseClicked

    }//GEN-LAST:event_ArticuloMouseClicked

    private void ReservasCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservasCliMouseClicked
        String cli = ListaCli.getSelectedItem().toString();
        if(ReservasCli.getModel().getSize() != 0){
            String NroRes = ReservasCli.getSelectedValue().toString();
            DtReserva DtRes = ICReserva.ObtenerDatosReserva(Integer.parseInt(NroRes));
            FCCli.setText(Integer.toString(DtRes.getDate().getDia()) +"/"+ DtRes.getDate().getMes()+"/"+ DtRes.getDate().getAnio());
            PrecioCli.setText(Float.toString(DtRes.getPrecio()));
            ArrayList<DtInfoReserva> ListInfoRes = DtRes.getInfoReserva();
            list3.clear();
            ListInfoRes.forEach(i -> list3.addElement(i.getNameArticulo()));
            Articulo.setModel(list3);
        }

    }//GEN-LAST:event_ReservasCliMouseClicked

    private void ListaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaCliActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ListaCli.setModel(new DefaultComboBoxModel(ICUsuario.listarClientes().toArray()));
        
        NomCli.setVisible(false);
        ApeCli.setVisible(false);
        AnioCli.setVisible(false);
        MesCli.setVisible(false);
        DiaCli.setVisible(false);
        EmailCli.setVisible(false);
        FCCli.setVisible(false);
        PrecioCli.setVisible(false);
        list2.clear();
        
        NomCli.setEnabled(false);
        ApeCli.setEnabled(false);
        AnioCli.setEnabled(false);
        MesCli.setEnabled(false);
        DiaCli.setEnabled(false);
        EmailCli.setEnabled(false);
        FCCli.setEnabled(false);
        PrecioCli.setEnabled(false);
        
        NomCli.setText("");
        ApeCli.setText("");
        AnioCli.setText("");
        MesCli.setText("");
        DiaCli.setText("");
        EmailCli.setText("");
        FCCli.setText("");
        PrecioCli.setText("");
        list3.clear();
        Articulo.setModel(list3);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnioCli;
    private javax.swing.JLabel ApeCli;
    private javax.swing.JList<String> Articulo;
    private javax.swing.JLabel DiaCli;
    private javax.swing.JLabel EmailCli;
    private javax.swing.JLabel FCCli;
    private javax.swing.JComboBox<String> ListaCli;
    private javax.swing.JLabel MesCli;
    private javax.swing.JLabel NomCli;
    private javax.swing.JLabel PrecioCli;
    private javax.swing.JList<String> ReservasCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel186;
    private javax.swing.JLabel jLabel187;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel214;
    private javax.swing.JLabel jLabel216;
    private javax.swing.JLabel jLabel217;
    private javax.swing.JLabel jLabel218;
    private javax.swing.JLabel jLabel222;
    private javax.swing.JLabel jLabel223;
    private javax.swing.JLabel jLabel224;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JLabel lbl_avatarCliente;
    // End of variables declaration//GEN-END:variables
}
