/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package help4travelling;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Agustin
 */
public class ConsultarProveedor extends javax.swing.JFrame {
    DefaultListModel<String> list2 = new DefaultListModel<>();
    DefaultListModel<String> list3 = new DefaultListModel<>();
    private IControladorUsuario ICUsuario;
    private IControladorArticulo ICArticulo;
    /**
     * Creates new form AltaUsuario
     */
    public ConsultarProveedor() {
        initComponents();
        ICUsuario = Factory.GetInstance().getIControladorUsuario();
        ICArticulo = Factory.GetInstance().getIControladorArticulo();
    }
    
    private Image ScaledImage(Image img, int w, int h){
        BufferedImage resizedImage = new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = resizedImage.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(img, 0, 0, w, h,null);
        g2.dispose();
        return resizedImage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel181 = new javax.swing.JLabel();
        jLabel182 = new javax.swing.JLabel();
        jLabel183 = new javax.swing.JLabel();
        cmb_proveedorP = new javax.swing.JComboBox<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        jList_ServiciosP = new javax.swing.JList<>();
        jLabel189 = new javax.swing.JLabel();
        jLabel190 = new javax.swing.JLabel();
        jLabel191 = new javax.swing.JLabel();
        jLabel193 = new javax.swing.JLabel();
        jLabel194 = new javax.swing.JLabel();
        jLabel195 = new javax.swing.JLabel();
        jLabel196 = new javax.swing.JLabel();
        jLabel198 = new javax.swing.JLabel();
        txt_LinkEmpresaP = new javax.swing.JLabel();
        jLabel201 = new javax.swing.JLabel();
        jLabel202 = new javax.swing.JLabel();
        lbl_avatarProveedor = new javax.swing.JLabel();
        jLabel204 = new javax.swing.JLabel();
        jLabel205 = new javax.swing.JLabel();
        jLabel203 = new javax.swing.JLabel();
        txt_DescripcionP = new javax.swing.JLabel();
        txt_ApellidoP = new javax.swing.JLabel();
        txt_emailP = new javax.swing.JLabel();
        tex_anio = new javax.swing.JLabel();
        txt_NombreP = new javax.swing.JLabel();
        tex_origen = new javax.swing.JLabel();
        tex_destino = new javax.swing.JLabel();
        txt_NombreEmpresaP = new javax.swing.JLabel();
        tex_dia = new javax.swing.JLabel();
        tex_mes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setBounds(new java.awt.Rectangle(0, 0, 1218, 707));
        setMaximumSize(new java.awt.Dimension(1218, 707));
        setMinimumSize(new java.awt.Dimension(1218, 707));
        setPreferredSize(new java.awt.Dimension(1218, 707));
        setResizable(false);
        setSize(new java.awt.Dimension(1218, 707));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1220, 10));

        jLabel181.setBackground(java.awt.Color.darkGray);
        jLabel181.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel181.setForeground(java.awt.Color.darkGray);
        jLabel181.setText("Servicios ofrecidos");
        getContentPane().add(jLabel181, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jLabel182.setBackground(java.awt.Color.darkGray);
        jLabel182.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel182.setForeground(java.awt.Color.darkGray);
        jLabel182.setText("PROVEEDORES");
        getContentPane().add(jLabel182, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel183.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/confirmar.png"))); // NOI18N
        jLabel183.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel183.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel183.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel183.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel183.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel183MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel183, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 610, 43, 43));

        cmb_proveedorP.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cmb_proveedorP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_proveedorP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_proveedorPItemStateChanged(evt);
            }
        });
        getContentPane().add(cmb_proveedorP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 240, -1));

        jList_ServiciosP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_ServiciosPMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(jList_ServiciosP);

        getContentPane().add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 240, 290));

        jLabel189.setBackground(java.awt.Color.darkGray);
        jLabel189.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel189.setForeground(java.awt.Color.darkGray);
        jLabel189.setText("Ciudad Destino");
        getContentPane().add(jLabel189, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, -1, -1));

        jLabel190.setBackground(java.awt.Color.darkGray);
        jLabel190.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel190.setForeground(java.awt.Color.darkGray);
        jLabel190.setText("Descripcion");
        getContentPane().add(jLabel190, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));

        jLabel191.setBackground(java.awt.Color.darkGray);
        jLabel191.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel191.setForeground(java.awt.Color.darkGray);
        jLabel191.setText("Imagenes");
        getContentPane().add(jLabel191, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, -1, -1));

        jLabel193.setBackground(java.awt.Color.darkGray);
        jLabel193.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel193.setForeground(java.awt.Color.darkGray);
        jLabel193.setText("Ciudad Origen");
        getContentPane().add(jLabel193, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, -1, -1));

        jLabel194.setBackground(new java.awt.Color(255, 255, 255));
        jLabel194.setOpaque(true);
        getContentPane().add(jLabel194, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 220, 130));

        jLabel195.setBackground(new java.awt.Color(255, 255, 255));
        jLabel195.setOpaque(true);
        getContentPane().add(jLabel195, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, 220, 130));

        jLabel196.setBackground(new java.awt.Color(255, 255, 255));
        jLabel196.setOpaque(true);
        getContentPane().add(jLabel196, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 230, 130));

        jLabel198.setBackground(java.awt.Color.darkGray);
        jLabel198.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel198.setForeground(java.awt.Color.darkGray);
        jLabel198.setText("Fecha Nacimiento");
        getContentPane().add(jLabel198, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txt_LinkEmpresaP.setBackground(java.awt.Color.darkGray);
        txt_LinkEmpresaP.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        txt_LinkEmpresaP.setForeground(java.awt.Color.darkGray);
        getContentPane().add(txt_LinkEmpresaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 240, 20));

        jLabel201.setBackground(java.awt.Color.darkGray);
        jLabel201.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel201.setForeground(java.awt.Color.darkGray);
        jLabel201.setText("Apellido");
        getContentPane().add(jLabel201, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel202.setBackground(java.awt.Color.darkGray);
        jLabel202.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel202.setForeground(java.awt.Color.darkGray);
        jLabel202.setText("E-mail");
        getContentPane().add(jLabel202, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        getContentPane().add(lbl_avatarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 400, 210));

        jLabel204.setBackground(java.awt.Color.darkGray);
        jLabel204.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel204.setForeground(java.awt.Color.darkGray);
        jLabel204.setText("Nombre empresa");
        getContentPane().add(jLabel204, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel205.setBackground(java.awt.Color.darkGray);
        jLabel205.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel205.setForeground(java.awt.Color.darkGray);
        jLabel205.setText("Link empresa");
        getContentPane().add(jLabel205, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel203.setBackground(java.awt.Color.darkGray);
        jLabel203.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel203.setForeground(java.awt.Color.darkGray);
        jLabel203.setText("Nombre");
        getContentPane().add(jLabel203, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txt_DescripcionP.setBackground(java.awt.Color.darkGray);
        txt_DescripcionP.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        txt_DescripcionP.setForeground(java.awt.Color.darkGray);
        txt_DescripcionP.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(txt_DescripcionP, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 370, 220));

        txt_ApellidoP.setBackground(java.awt.Color.darkGray);
        txt_ApellidoP.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        txt_ApellidoP.setForeground(java.awt.Color.darkGray);
        getContentPane().add(txt_ApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 240, 20));

        txt_emailP.setBackground(java.awt.Color.darkGray);
        txt_emailP.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        txt_emailP.setForeground(java.awt.Color.darkGray);
        getContentPane().add(txt_emailP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 240, 20));

        tex_anio.setBackground(java.awt.Color.darkGray);
        tex_anio.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        tex_anio.setForeground(java.awt.Color.darkGray);
        getContentPane().add(tex_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 50, 20));

        txt_NombreP.setBackground(new java.awt.Color(255, 255, 255));
        txt_NombreP.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        getContentPane().add(txt_NombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 240, 20));

        tex_origen.setBackground(java.awt.Color.darkGray);
        tex_origen.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        tex_origen.setForeground(java.awt.Color.darkGray);
        getContentPane().add(tex_origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 240, 20));

        tex_destino.setBackground(java.awt.Color.darkGray);
        tex_destino.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        tex_destino.setForeground(java.awt.Color.darkGray);
        getContentPane().add(tex_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 240, 20));

        txt_NombreEmpresaP.setBackground(java.awt.Color.darkGray);
        txt_NombreEmpresaP.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        txt_NombreEmpresaP.setForeground(java.awt.Color.darkGray);
        getContentPane().add(txt_NombreEmpresaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 240, 20));

        tex_dia.setBackground(java.awt.Color.darkGray);
        tex_dia.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        tex_dia.setForeground(java.awt.Color.darkGray);
        getContentPane().add(tex_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 50, 20));

        tex_mes.setBackground(java.awt.Color.darkGray);
        tex_mes.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        tex_mes.setForeground(java.awt.Color.darkGray);
        getContentPane().add(tex_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 50, 20));

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setEnabled(false);
        jLabel1.setFocusable(false);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1218, 590));

        jLabel3.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Ver información de proveedor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/banner2.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel183MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel183MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel183MouseClicked

    private void cmb_proveedorPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_proveedorPItemStateChanged
        txt_NombreP.setText("");
        txt_ApellidoP.setText("");
        txt_emailP.setText("");
        txt_NombreEmpresaP.setText("");
        txt_LinkEmpresaP.setText("");
        txt_DescripcionP.setText("");
        tex_anio.setText("");
        tex_mes.setText("");
        tex_dia.setText("");
        tex_origen.setText("");
        tex_destino.setText("");
        list2.clear();

        String prov = cmb_proveedorP.getSelectedItem().toString();
        DtProveedor DtProv = ICUsuario.datosProveedor(prov);

        lbl_avatarProveedor.setIcon(null);
        if(ManejadorSQL.GetInstance().selectImgUsuario(DtProv.getNick().trim()) != null){
            Image a =  new ImageIcon(ManejadorSQL.GetInstance().selectImgUsuario(DtProv.getNick().trim())).getImage();
            ImageIcon icon = new ImageIcon(a);
            lbl_avatarProveedor.setIcon(icon);
        }

        txt_NombreP.setVisible(true);
        txt_ApellidoP.setVisible(true);
        txt_emailP.setVisible(true);
        txt_NombreEmpresaP.setVisible(true);
        txt_LinkEmpresaP.setVisible(true);

        tex_anio.setVisible(true);
        tex_mes.setVisible(true);
        tex_dia.setVisible(true);
        txt_NombreP.setText(DtProv.getNombre());
        txt_ApellidoP.setText(DtProv.getApellido());
        txt_emailP.setText(DtProv.getEmail());
        txt_NombreEmpresaP.setText(DtProv.getNombreEmpresa());
        txt_LinkEmpresaP.setText(DtProv.getUrl());
        tex_anio.setText(Integer.toString(DtProv.getFechaN().getAnio()));
        tex_mes.setText(Integer.toString(DtProv.getFechaN().getMes()));
        tex_dia.setText(Integer.toString(DtProv.getFechaN().getDia()));

        //txt_DescripcionP.setText(DtProv.)
        java.util.List<DtServicio> listdtServ = new ArrayList();
        listdtServ = DtProv.getServicio();

        java.util.List<String> lista = new ArrayList();

        //listdtServ.forEach(i -> lista.add(((DtServicio)i).getNombre()));
        if(!list2.contains(jList_ServiciosP.getSelectedValue())){
            listdtServ.forEach(i -> list2.addElement(((DtServicio)i).getNombre()));
        }
        //cmb_servicio.setModel(new DefaultComboBoxModel(lista.toArray()));
        //list2.addElement(lista);
        jList_ServiciosP.setModel(list2);
    }//GEN-LAST:event_cmb_proveedorPItemStateChanged

    private void jList_ServiciosPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_ServiciosPMouseClicked
        if(jList_ServiciosP.getModel().getSize() != 0){
            txt_DescripcionP.setText("");
            tex_origen.setText("");
            tex_destino.setText("");
            tex_origen.setVisible(true);
            tex_destino.setVisible(true);
            txt_DescripcionP.setVisible(true);
            String NameServ = jList_ServiciosP.getSelectedValue();
            String prov = cmb_proveedorP.getSelectedItem().toString();
            DtServicio DtServ = ICArticulo.datosServicio(NameServ, prov);
            txt_DescripcionP.setText(DtServ.getDescripcion());
            tex_origen.setText(DtServ.getCiudadOrigen());
            tex_destino.setText(DtServ.getCiudadDestino());
            
            jLabel194.setIcon(null);
            if(ManejadorSQL.GetInstance().selectImgServicio("imagen1", DtServ.getNickProveedor().trim(), DtServ.getNombre().trim()) != null){
                Image a =  new ImageIcon(ManejadorSQL.GetInstance().selectImgServicio("imagen1", DtServ.getNickProveedor().trim(), DtServ.getNombre().trim())).getImage();
                ImageIcon icon = new ImageIcon(ScaledImage(a,jLabel194.getWidth(),jLabel194.getHeight()));
                jLabel194.setIcon(icon);
            }
            
            jLabel196.setIcon(null);
            if(ManejadorSQL.GetInstance().selectImgServicio("imagen2", DtServ.getNickProveedor().trim(), DtServ.getNombre().trim()) != null){
                Image a =  new ImageIcon(ManejadorSQL.GetInstance().selectImgServicio("imagen2", DtServ.getNickProveedor().trim(), DtServ.getNombre().trim())).getImage();
                ImageIcon icon = new ImageIcon(ScaledImage(a,jLabel196.getWidth(),jLabel196.getHeight()));
                jLabel196.setIcon(icon);
            }
            
            jLabel195.setIcon(null);
            if(ManejadorSQL.GetInstance().selectImgServicio("imagen3", DtServ.getNickProveedor().trim(), DtServ.getNombre().trim()) != null){
                Image a =  new ImageIcon(ManejadorSQL.GetInstance().selectImgServicio("imagen3", DtServ.getNickProveedor().trim(), DtServ.getNombre().trim())).getImage();
                ImageIcon icon = new ImageIcon(ScaledImage(a,jLabel195.getWidth(),jLabel195.getHeight()));
                jLabel195.setIcon(icon);
            }
        }
    }//GEN-LAST:event_jList_ServiciosPMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cmb_proveedorP.setModel(new DefaultComboBoxModel(ICUsuario.listarProveedores().toArray()));
        txt_NombreP.setEnabled(false);
        txt_ApellidoP.setEnabled(false);
        txt_emailP.setEnabled(false);
        txt_NombreEmpresaP.setEnabled(false);
        txt_LinkEmpresaP.setEnabled(false);
        txt_DescripcionP.setEnabled(false);
        tex_anio.setEnabled(false);
        tex_mes.setEnabled(false);
        tex_dia.setEnabled(false);
        tex_origen.setEnabled(false);
        tex_destino.setEnabled(false);
        list2.clear();
        txt_NombreP.setText("");
        txt_ApellidoP.setText("");
        txt_emailP.setText("");
        txt_NombreEmpresaP.setText("");
        txt_LinkEmpresaP.setText("");
        txt_DescripcionP.setText("");
        tex_anio.setText("");
        tex_mes.setText("");
        tex_dia.setText("");
        tex_origen.setText("");
        tex_destino.setText("");
        
        txt_NombreP.setVisible(false);
        txt_ApellidoP.setVisible(false);
        txt_emailP.setVisible(false);
        txt_NombreEmpresaP.setVisible(false);
        txt_LinkEmpresaP.setVisible(false);
        txt_DescripcionP.setVisible(false);
        tex_anio.setVisible(false);
        tex_mes.setVisible(false);
        tex_dia.setVisible(false);
        tex_origen.setVisible(false);
        tex_destino.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_proveedorP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel181;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabel190;
    private javax.swing.JLabel jLabel191;
    private javax.swing.JLabel jLabel193;
    private javax.swing.JLabel jLabel194;
    private javax.swing.JLabel jLabel195;
    private javax.swing.JLabel jLabel196;
    private javax.swing.JLabel jLabel198;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel201;
    private javax.swing.JLabel jLabel202;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList_ServiciosP;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JLabel lbl_avatarProveedor;
    private javax.swing.JLabel tex_anio;
    private javax.swing.JLabel tex_destino;
    private javax.swing.JLabel tex_dia;
    private javax.swing.JLabel tex_mes;
    private javax.swing.JLabel tex_origen;
    private javax.swing.JLabel txt_ApellidoP;
    private javax.swing.JLabel txt_DescripcionP;
    private javax.swing.JLabel txt_LinkEmpresaP;
    private javax.swing.JLabel txt_NombreEmpresaP;
    private javax.swing.JLabel txt_NombreP;
    private javax.swing.JLabel txt_emailP;
    // End of variables declaration//GEN-END:variables
}
