/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package help4travelling;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Agustin
 */
public class IngresarCategoria extends javax.swing.JFrame {
    private IControladorCategoria ICCategoria;
    /**
     * Creates new form AltaUsuario
     */
    public IngresarCategoria() {
        initComponents();
        ICCategoria = Factory.GetInstance().getIControladorCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        txt_categoria = new javax.swing.JTextField();
        lab_categoria = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        cmb_categoria = new javax.swing.JComboBox<>();
        chek_padre = new java.awt.Checkbox();
        jLabel42 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setBounds(new java.awt.Rectangle(0, 0, 1218, 707));
        setMinimumSize(new java.awt.Dimension(1218, 707));
        setResizable(false);
        setSize(new java.awt.Dimension(1218, 707));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1220, 10));

        jLabel104.setBackground(java.awt.Color.darkGray);
        jLabel104.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel104.setForeground(java.awt.Color.darkGray);
        jLabel104.setText("Nombre");
        getContentPane().add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txt_categoria.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        getContentPane().add(txt_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 320, -1));

        lab_categoria.setBackground(java.awt.Color.darkGray);
        lab_categoria.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        lab_categoria.setForeground(java.awt.Color.darkGray);
        lab_categoria.setText("Categoria Padre");
        getContentPane().add(lab_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        lab_categoria.setVisible(false);

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/confirmar.png"))); // NOI18N
        jLabel74.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel74.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel74.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel74.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel74.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel74MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 650, 43, 43));

        cmb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_categoriaActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 260, -1));
        cmb_categoria.setVisible(false);

        chek_padre.setBackground(java.awt.Color.white);
        chek_padre.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        chek_padre.setLabel("Asignar categoria padre");
        chek_padre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chek_padreMouseClicked(evt);
            }
        });
        chek_padre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chek_padreItemStateChanged(evt);
            }
        });
        getContentPane().add(chek_padre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/error.png"))); // NOI18N
        jLabel42.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 650, 42, 42));

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setEnabled(false);
        jLabel1.setFocusable(false);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1218, 590));

        jLabel3.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Ingreso de categoría");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/banner2.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel74MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel74MouseClicked
        if(txt_categoria.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese un nombre para la categoria, verifique y vuelva a intentar.","Compos sin completar",JOptionPane.WARNING_MESSAGE);
        }else if(chek_padre.getState()){
            if(!ICCategoria.IngresarCategoria(txt_categoria.getText(), cmb_categoria.getSelectedItem().toString()))
                JOptionPane.showMessageDialog(null, "Ya existe una categoria con ese nombre.","Error",JOptionPane.WARNING_MESSAGE);
            else{
                txt_categoria.setText("");
                JOptionPane.showMessageDialog(null, "Categoria ingresado");
                chek_padre.setState(false);
                lab_categoria.setVisible(false);
                cmb_categoria.setVisible(false);
            }
        }
        else{
            if (!ICCategoria.IngresarCategoria(txt_categoria.getText()))
                JOptionPane.showMessageDialog(null, "Ya existe una categoria con ese nombre.","Error",JOptionPane.WARNING_MESSAGE);
            else{
                txt_categoria.setText("");
                JOptionPane.showMessageDialog(null, "Categoria ingresado");
                chek_padre.setState(false);
                lab_categoria.setVisible(false);
                cmb_categoria.setVisible(false);
            }            
        }
    }//GEN-LAST:event_jLabel74MouseClicked

    private void cmb_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_categoriaActionPerformed

    private void chek_padreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chek_padreMouseClicked
        if (chek_padre.getState()){
            lab_categoria.setVisible(true);
            cmb_categoria.setVisible(true);
        }
        else{
            lab_categoria.setVisible(false);
            cmb_categoria.setVisible(false);
        }
    }//GEN-LAST:event_chek_padreMouseClicked

    private void chek_padreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chek_padreItemStateChanged
        if (chek_padre.getState()){
            lab_categoria.setVisible(true);
            cmb_categoria.setVisible(true);
        }
        else{
            lab_categoria.setVisible(false);
            cmb_categoria.setVisible(false);
        }
    }//GEN-LAST:event_chek_padreItemStateChanged

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel42MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //listar categorias!
        //devuelve arry list dtcategoria
        ArrayList<DtCategoria> listdtcat = new ArrayList();
        listdtcat = ICCategoria.listarCategorias();
        ArrayList<String> lista = new ArrayList();
        listdtcat.forEach(i -> lista.add(((DtCategoria)i).getNombre()));
        //cmb_categoria = new JComboBox(lista.toArray();
        cmb_categoria.setModel(new DefaultComboBoxModel(lista.toArray()));
        lab_categoria.setVisible(false);
        cmb_categoria.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox chek_padre;
    private javax.swing.JComboBox<String> cmb_categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lab_categoria;
    private javax.swing.JTextField txt_categoria;
    // End of variables declaration//GEN-END:variables
}
