package help4travelling;

import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Agustin
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_promociones = new javax.swing.JLabel();
        btn_categorias = new javax.swing.JLabel();
        btn_servicios = new javax.swing.JLabel();
        btn_reservas = new javax.swing.JLabel();
        btn_usuarios = new javax.swing.JLabel();
        btn_registros = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_menu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_mostrar_registros1 = new javax.swing.JLabel();
        panel_usuarios = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        consultar_cliente = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ingresar_usuario = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        consultar_proveedor = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        panel_servicios = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        consultar_servicio = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ingresar_servicio = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        actualizar_servicio = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        panel_promociones = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        consultar_promocion = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ingresar_promocion = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panel_reservas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        consultar_reserva = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        cancelar_reserva = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        actualizar_estado = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panel_categorias = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        ingresar_categoria = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        panel_registros = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        consultar_serviciosMasVisitados = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        consultar_registros = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        btn_promociones1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setBounds(new java.awt.Rectangle(0, 0, 1218, 707));
        setMinimumSize(new java.awt.Dimension(1218, 707));
        setResizable(false);
        setSize(new java.awt.Dimension(1218, 707));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_promociones.setBackground(new java.awt.Color(51, 51, 51));
        btn_promociones.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        btn_promociones.setForeground(new java.awt.Color(254, 254, 254));
        btn_promociones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_promociones.setText("PROMOCIONES");
        btn_promociones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_promociones.setName("btn_promociones"); // NOI18N
        btn_promociones.setOpaque(true);
        btn_promociones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_promocionesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_promocionesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_promocionesMouseEntered(evt);
            }
        });
        getContentPane().add(btn_promociones, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 190, 40));

        btn_categorias.setBackground(new java.awt.Color(51, 51, 51));
        btn_categorias.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        btn_categorias.setForeground(new java.awt.Color(254, 254, 254));
        btn_categorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_categorias.setText("CATEGORIAS");
        btn_categorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_categorias.setName("lbl_mostrar_registros"); // NOI18N
        btn_categorias.setOpaque(true);
        btn_categorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_categoriasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_categoriasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_categoriasMouseExited(evt);
            }
        });
        getContentPane().add(btn_categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 190, 40));

        btn_servicios.setBackground(new java.awt.Color(51, 51, 51));
        btn_servicios.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        btn_servicios.setForeground(new java.awt.Color(254, 254, 254));
        btn_servicios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_servicios.setText("SERVICIOS");
        btn_servicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_servicios.setName("lbl_mostrar_registros"); // NOI18N
        btn_servicios.setOpaque(true);
        btn_servicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_serviciosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_serviciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_serviciosMouseExited(evt);
            }
        });
        getContentPane().add(btn_servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 190, 40));

        btn_reservas.setBackground(new java.awt.Color(51, 51, 51));
        btn_reservas.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        btn_reservas.setForeground(new java.awt.Color(254, 254, 254));
        btn_reservas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_reservas.setText("RESERVAS");
        btn_reservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reservas.setName("lbl_mostrar_registros"); // NOI18N
        btn_reservas.setOpaque(true);
        btn_reservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_reservasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_reservasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_reservasMouseExited(evt);
            }
        });
        getContentPane().add(btn_reservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 190, 40));

        btn_usuarios.setBackground(new java.awt.Color(51, 51, 51));
        btn_usuarios.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        btn_usuarios.setForeground(new java.awt.Color(254, 254, 254));
        btn_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_usuarios.setText("USUARIOS");
        btn_usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_usuarios.setName("lbl_mostrar_registros"); // NOI18N
        btn_usuarios.setOpaque(true);
        btn_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_usuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_usuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_usuariosMouseExited(evt);
            }
        });
        getContentPane().add(btn_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 190, 40));

        btn_registros.setBackground(new java.awt.Color(51, 51, 51));
        btn_registros.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        btn_registros.setForeground(new java.awt.Color(254, 254, 254));
        btn_registros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_registros.setText("REGISTROS");
        btn_registros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registros.setName("btn_promociones"); // NOI18N
        btn_registros.setOpaque(true);
        btn_registros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrosMouseExited(evt);
            }
        });
        getContentPane().add(btn_registros, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 220, 190, 40));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1220, 40));

        lbl_menu.setBackground(new java.awt.Color(1, 82, 160));
        lbl_menu.setFont(new java.awt.Font("FreeSans", 0, 36)); // NOI18N
        lbl_menu.setForeground(java.awt.Color.white);
        lbl_menu.setText("                                           ");
        lbl_menu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbl_menu.setOpaque(true);
        getContentPane().add(lbl_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1220, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/banner.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 220));

        lbl_mostrar_registros1.setBackground(new java.awt.Color(51, 51, 51));
        lbl_mostrar_registros1.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        lbl_mostrar_registros1.setForeground(new java.awt.Color(254, 254, 254));
        lbl_mostrar_registros1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_mostrar_registros1.setText("CATEGORIAS");
        lbl_mostrar_registros1.setName("lbl_mostrar_registros"); // NOI18N
        lbl_mostrar_registros1.setOpaque(true);
        getContentPane().add(lbl_mostrar_registros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 190, 40));

        panel_usuarios.setBackground(java.awt.Color.darkGray);
        panel_usuarios.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/salir.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setFocusable(false);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        panel_usuarios.add(jLabel4);
        jLabel4.setBounds(1183, 0, 30, 30);

        jLabel30.setBackground(new java.awt.Color(33, 33, 33));
        jLabel30.setOpaque(true);
        panel_usuarios.add(jLabel30);
        jLabel30.setBounds(0, 0, 1220, 30);

        consultar_cliente.setBackground(java.awt.Color.darkGray);
        consultar_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultar_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultar_clienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultar_clienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultar_clienteMouseExited(evt);
            }
        });
        consultar_cliente.setLayout(null);

        jLabel11.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("CONSULTAR CLIENTE");
        consultar_cliente.add(jLabel11);
        jLabel11.setBounds(40, 90, 200, 20);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/search.png"))); // NOI18N
        jLabel23.setText("jLabel19");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel23MouseEntered(evt);
            }
        });
        consultar_cliente.add(jLabel23);
        jLabel23.setBounds(120, 45, 43, 43);

        panel_usuarios.add(consultar_cliente);
        consultar_cliente.setBounds(750, 30, 290, 180);

        ingresar_usuario.setBackground(java.awt.Color.darkGray);
        ingresar_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresar_usuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresar_usuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresar_usuarioMouseExited(evt);
            }
        });
        ingresar_usuario.setLayout(null);

        jLabel10.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("INGRESAR USUARIO");
        ingresar_usuario.add(jLabel10);
        jLabel10.setBounds(50, 90, 180, 20);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/add.png"))); // NOI18N
        jLabel20.setText("jLabel19");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
        });
        ingresar_usuario.add(jLabel20);
        jLabel20.setBounds(120, 40, 42, 42);

        panel_usuarios.add(ingresar_usuario);
        ingresar_usuario.setBounds(460, 30, 290, 180);

        consultar_proveedor.setBackground(java.awt.Color.darkGray);
        consultar_proveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultar_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultar_proveedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultar_proveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultar_proveedorMouseExited(evt);
            }
        });
        consultar_proveedor.setLayout(null);

        jLabel12.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("CONSULTAR PROVEEDOR");
        consultar_proveedor.add(jLabel12);
        jLabel12.setBounds(30, 90, 230, 20);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/search.png"))); // NOI18N
        jLabel28.setText("jLabel19");
        jLabel28.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel28MouseEntered(evt);
            }
        });
        consultar_proveedor.add(jLabel28);
        jLabel28.setBounds(120, 45, 43, 43);

        panel_usuarios.add(consultar_proveedor);
        consultar_proveedor.setBounds(170, 30, 290, 180);

        getContentPane().add(panel_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 120, 140));
        getContentPane().remove(panel_usuarios);
        getContentPane().add(panel_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1220, 210));
        panel_usuarios.setVisible(false);

        panel_servicios.setBackground(java.awt.Color.darkGray);
        panel_servicios.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/salir.png"))); // NOI18N
        jLabel5.setText("jLabel4");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setFocusable(false);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        panel_servicios.add(jLabel5);
        jLabel5.setBounds(1183, 0, 30, 30);

        consultar_servicio.setBackground(java.awt.Color.darkGray);
        consultar_servicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultar_servicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultar_servicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultar_servicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultar_servicioMouseExited(evt);
            }
        });
        consultar_servicio.setLayout(null);

        jLabel13.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("VER INFORMACIÓN");
        consultar_servicio.add(jLabel13);
        jLabel13.setBounds(60, 90, 170, 20);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/search.png"))); // NOI18N
        jLabel25.setText("jLabel19");
        jLabel25.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
        });
        consultar_servicio.add(jLabel25);
        jLabel25.setBounds(120, 45, 42, 42);

        panel_servicios.add(consultar_servicio);
        consultar_servicio.setBounds(750, 30, 290, 180);

        ingresar_servicio.setBackground(java.awt.Color.darkGray);
        ingresar_servicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar_servicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresar_servicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresar_servicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresar_servicioMouseExited(evt);
            }
        });
        ingresar_servicio.setLayout(null);

        jLabel14.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("INGRESAR");
        ingresar_servicio.add(jLabel14);
        jLabel14.setBounds(95, 90, 100, 20);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/add.png"))); // NOI18N
        jLabel26.setText("jLabel19");
        jLabel26.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel26MouseEntered(evt);
            }
        });
        ingresar_servicio.add(jLabel26);
        jLabel26.setBounds(120, 45, 42, 42);

        panel_servicios.add(ingresar_servicio);
        ingresar_servicio.setBounds(460, 30, 290, 180);

        actualizar_servicio.setBackground(java.awt.Color.darkGray);
        actualizar_servicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actualizar_servicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizar_servicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                actualizar_servicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                actualizar_servicioMouseExited(evt);
            }
        });
        actualizar_servicio.setLayout(null);

        jLabel15.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("ACTUALIZAR");
        actualizar_servicio.add(jLabel15);
        jLabel15.setBounds(95, 95, 120, 20);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/modifyy.png"))); // NOI18N
        jLabel27.setText("jLabel19");
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel27MouseEntered(evt);
            }
        });
        actualizar_servicio.add(jLabel27);
        jLabel27.setBounds(127, 47, 43, 43);

        panel_servicios.add(actualizar_servicio);
        actualizar_servicio.setBounds(170, 30, 290, 180);

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setEnabled(false);
        jLabel1.setFocusable(false);
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        panel_servicios.add(jLabel1);
        jLabel1.setBounds(-640, -20, 1218, 560);

        jLabel31.setBackground(new java.awt.Color(33, 33, 33));
        jLabel31.setOpaque(true);
        panel_servicios.add(jLabel31);
        jLabel31.setBounds(0, 0, 130, 110);

        getContentPane().add(panel_servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 120, 110));
        getContentPane().remove(panel_servicios);
        getContentPane().add(panel_servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1220, 210));
        panel_servicios.setVisible(false);

        panel_promociones.setBackground(java.awt.Color.darkGray);
        panel_promociones.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/salir.png"))); // NOI18N
        jLabel6.setText("jLabel4");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setFocusable(false);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        panel_promociones.add(jLabel6);
        jLabel6.setBounds(1183, 0, 30, 30);

        jLabel32.setBackground(new java.awt.Color(33, 33, 33));
        jLabel32.setOpaque(true);
        panel_promociones.add(jLabel32);
        jLabel32.setBounds(0, 0, 1220, 30);

        consultar_promocion.setBackground(java.awt.Color.darkGray);
        consultar_promocion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultar_promocion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultar_promocionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultar_promocionMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultar_promocionMouseEntered(evt);
            }
        });
        consultar_promocion.setLayout(null);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/search.png"))); // NOI18N
        jLabel29.setText("jLabel19");
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel29MouseEntered(evt);
            }
        });
        consultar_promocion.add(jLabel29);
        jLabel29.setBounds(120, 45, 42, 42);

        jLabel16.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("VER INFORMACIÓN");
        consultar_promocion.add(jLabel16);
        jLabel16.setBounds(60, 90, 170, 20);

        panel_promociones.add(consultar_promocion);
        consultar_promocion.setBounds(600, 30, 290, 180);

        ingresar_promocion.setBackground(java.awt.Color.darkGray);
        ingresar_promocion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar_promocion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresar_promocionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresar_promocionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresar_promocionMouseExited(evt);
            }
        });
        ingresar_promocion.setLayout(null);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/add.png"))); // NOI18N
        jLabel33.setText("jLabel19");
        jLabel33.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel33MouseEntered(evt);
            }
        });
        ingresar_promocion.add(jLabel33);
        jLabel33.setBounds(125, 45, 42, 42);

        jLabel17.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("INGRESAR");
        ingresar_promocion.add(jLabel17);
        jLabel17.setBounds(100, 90, 100, 20);

        panel_promociones.add(ingresar_promocion);
        ingresar_promocion.setBounds(310, 30, 290, 180);

        getContentPane().add(panel_promociones, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, 100, 100));
        getContentPane().remove(panel_promociones);
        getContentPane().add(panel_promociones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1220, 210));
        panel_promociones.setVisible(false);

        panel_reservas.setBackground(java.awt.Color.darkGray);
        panel_reservas.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/salir.png"))); // NOI18N
        jLabel7.setText("jLabel4");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setFocusable(false);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        panel_reservas.add(jLabel7);
        jLabel7.setBounds(1183, 0, 30, 30);

        jLabel34.setBackground(new java.awt.Color(33, 33, 33));
        jLabel34.setOpaque(true);
        panel_reservas.add(jLabel34);
        jLabel34.setBounds(0, 0, 1220, 30);

        consultar_reserva.setBackground(java.awt.Color.darkGray);
        consultar_reserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultar_reserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultar_reservaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultar_reservaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultar_reservaMouseExited(evt);
            }
        });
        consultar_reserva.setLayout(null);

        jLabel18.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("VER INFORMACIÓN");
        consultar_reserva.add(jLabel18);
        jLabel18.setBounds(60, 90, 170, 20);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/search.png"))); // NOI18N
        jLabel35.setText("jLabel19");
        jLabel35.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel35MouseEntered(evt);
            }
        });
        consultar_reserva.add(jLabel35);
        jLabel35.setBounds(120, 45, 42, 42);

        panel_reservas.add(consultar_reserva);
        consultar_reserva.setBounds(740, 30, 290, 180);

        cancelar_reserva.setBackground(java.awt.Color.darkGray);
        cancelar_reserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelar_reserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelar_reservaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelar_reservaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelar_reservaMouseExited(evt);
            }
        });
        cancelar_reserva.setLayout(null);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/delete.png"))); // NOI18N
        jLabel37.setText("jLabel19");
        jLabel37.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel37MouseEntered(evt);
            }
        });
        cancelar_reserva.add(jLabel37);
        jLabel37.setBounds(125, 45, 43, 43);

        jLabel21.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setText("CANCELAR");
        cancelar_reserva.add(jLabel21);
        jLabel21.setBounds(100, 90, 100, 20);

        panel_reservas.add(cancelar_reserva);
        cancelar_reserva.setBounds(160, 30, 290, 180);

        actualizar_estado.setBackground(java.awt.Color.darkGray);
        actualizar_estado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actualizar_estado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizar_estadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                actualizar_estadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                actualizar_estadoMouseExited(evt);
            }
        });
        actualizar_estado.setLayout(null);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/modifyy.png"))); // NOI18N
        jLabel38.setText("jLabel19");
        jLabel38.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel38MouseEntered(evt);
            }
        });
        actualizar_estado.add(jLabel38);
        jLabel38.setBounds(125, 45, 43, 43);

        jLabel22.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        jLabel22.setForeground(java.awt.Color.white);
        jLabel22.setText("ACTUALIZAR ESTADO");
        actualizar_estado.add(jLabel22);
        jLabel22.setBounds(50, 90, 190, 20);

        panel_reservas.add(actualizar_estado);
        actualizar_estado.setBounds(450, 30, 290, 180);

        getContentPane().add(panel_reservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 140, 100));
        getContentPane().remove(panel_reservas);
        getContentPane().add(panel_reservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1220, 210));
        panel_reservas.setVisible(false);

        panel_categorias.setBackground(java.awt.Color.darkGray);
        panel_categorias.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/salir.png"))); // NOI18N
        jLabel9.setText("jLabel4");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setFocusable(false);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        panel_categorias.add(jLabel9);
        jLabel9.setBounds(1182, 0, 30, 30);

        jLabel36.setBackground(new java.awt.Color(33, 33, 33));
        jLabel36.setOpaque(true);
        panel_categorias.add(jLabel36);
        jLabel36.setBounds(0, 0, 1220, 30);

        ingresar_categoria.setBackground(java.awt.Color.darkGray);
        ingresar_categoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar_categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresar_categoriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresar_categoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresar_categoriaMouseExited(evt);
            }
        });
        ingresar_categoria.setLayout(null);

        jLabel39.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        jLabel39.setForeground(java.awt.Color.white);
        jLabel39.setText("INGRESAR");
        ingresar_categoria.add(jLabel39);
        jLabel39.setBounds(100, 90, 100, 20);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/add.png"))); // NOI18N
        jLabel40.setText("jLabel19");
        jLabel40.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel40MouseEntered(evt);
            }
        });
        ingresar_categoria.add(jLabel40);
        jLabel40.setBounds(125, 45, 42, 42);

        panel_categorias.add(ingresar_categoria);
        ingresar_categoria.setBounds(460, 30, 290, 180);

        getContentPane().add(panel_categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 120, 140));
        getContentPane().remove(panel_categorias);
        getContentPane().add(panel_categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1218, 210));
        panel_categorias.setVisible(false);

        panel_registros.setBackground(java.awt.Color.darkGray);
        panel_registros.setLayout(null);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/salir.png"))); // NOI18N
        jLabel19.setText("jLabel4");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.setFocusable(false);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        panel_registros.add(jLabel19);
        jLabel19.setBounds(1183, 0, 30, 30);

        jLabel41.setBackground(new java.awt.Color(33, 33, 33));
        jLabel41.setOpaque(true);
        panel_registros.add(jLabel41);
        jLabel41.setBounds(0, 0, 1220, 30);

        consultar_serviciosMasVisitados.setBackground(java.awt.Color.darkGray);
        consultar_serviciosMasVisitados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultar_serviciosMasVisitados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultar_serviciosMasVisitadosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultar_serviciosMasVisitadosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultar_serviciosMasVisitadosMouseEntered(evt);
            }
        });
        consultar_serviciosMasVisitados.setLayout(null);

        jLabel24.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        jLabel24.setForeground(java.awt.Color.white);
        jLabel24.setText("SERVICIOS MÁS VISITADOS");
        consultar_serviciosMasVisitados.add(jLabel24);
        jLabel24.setBounds(20, 90, 250, 20);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/search.png"))); // NOI18N
        jLabel45.setText("jLabel19");
        jLabel45.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel45.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel45MouseEntered(evt);
            }
        });
        consultar_serviciosMasVisitados.add(jLabel45);
        jLabel45.setBounds(120, 45, 42, 42);

        panel_registros.add(consultar_serviciosMasVisitados);
        consultar_serviciosMasVisitados.setBounds(600, 30, 290, 180);

        consultar_registros.setBackground(java.awt.Color.darkGray);
        consultar_registros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultar_registros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultar_registrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultar_registrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultar_registrosMouseExited(evt);
            }
        });
        consultar_registros.setLayout(null);

        jLabel44.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        jLabel44.setForeground(java.awt.Color.white);
        jLabel44.setText("ACCESOS AL SITIO");
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel44MouseEntered(evt);
            }
        });
        consultar_registros.add(jLabel44);
        jLabel44.setBounds(60, 90, 170, 20);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/search.png"))); // NOI18N
        jLabel42.setText("jLabel19");
        jLabel42.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel42MouseEntered(evt);
            }
        });
        consultar_registros.add(jLabel42);
        jLabel42.setBounds(125, 45, 42, 42);

        panel_registros.add(consultar_registros);
        consultar_registros.setBounds(310, 30, 290, 180);

        getContentPane().add(panel_registros, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 310, 100, 100));
        getContentPane().remove(panel_registros);
        getContentPane().add(panel_registros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1220, 210));
        panel_registros.setVisible(false);

        btn_promociones1.setBackground(new java.awt.Color(51, 51, 51));
        btn_promociones1.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        btn_promociones1.setForeground(new java.awt.Color(254, 254, 254));
        btn_promociones1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_promociones1.setText("PROMOCIONES");
        btn_promociones1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_promociones1.setName("btn_promociones"); // NOI18N
        btn_promociones1.setOpaque(true);
        btn_promociones1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_promociones1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_promociones1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_promociones1MouseExited(evt);
            }
        });
        getContentPane().add(btn_promociones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 190, 40));

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setEnabled(false);
        jLabel3.setFocusable(false);
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1218, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        btn_usuarios.setBackground(new Color(51, 51, 51));
        panel_usuarios.setVisible(false);
        panel_categorias.setVisible(false);
        panel_reservas.setVisible(false);

        panel_servicios.setVisible(false);
        panel_registros.setVisible(false);
        panel_promociones.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        ingresar_usuario.setBackground(Color.DARK_GRAY);
        IngresarUsuario iu = new IngresarUsuario();
        iu.setVisible(true);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void ingresar_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_usuarioMouseClicked
        IngresarUsuario iu = new IngresarUsuario();
        iu.setVisible(true);
    }//GEN-LAST:event_ingresar_usuarioMouseClicked

    private void ingresar_usuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_usuarioMouseExited
        ingresar_usuario.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_ingresar_usuarioMouseExited

    private void ingresar_usuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_usuarioMouseEntered
        ingresar_usuario.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_ingresar_usuarioMouseEntered

    private void btn_usuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMouseEntered
        btn_usuarios.setBackground(new Color(33, 33, 33));
    }//GEN-LAST:event_btn_usuariosMouseEntered

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        btn_servicios.setBackground(new Color(51, 51, 51));
        panel_servicios.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        consultar_servicio.setBackground(Color.darkGray);
        ConsultarServicio cs = new ConsultarServicio();
        cs.setVisible(true);
    }//GEN-LAST:event_jLabel25MouseClicked

    private void consultar_servicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_servicioMouseClicked
        ConsultarServicio cs = new ConsultarServicio();
        cs.setVisible(true);
    }//GEN-LAST:event_consultar_servicioMouseClicked

    private void consultar_servicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_servicioMouseExited
        consultar_servicio.setBackground(Color.darkGray);
    }//GEN-LAST:event_consultar_servicioMouseExited

    private void consultar_servicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_servicioMouseEntered
        consultar_servicio.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_consultar_servicioMouseEntered

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        ingresar_servicio.setBackground(Color.darkGray);
        IngresarServicio is = new IngresarServicio();
        is.setVisible(true);
    }//GEN-LAST:event_jLabel26MouseClicked

    private void ingresar_servicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_servicioMouseClicked
        IngresarServicio is = new IngresarServicio();
        is.setVisible(true);
    }//GEN-LAST:event_ingresar_servicioMouseClicked

    private void ingresar_servicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_servicioMouseExited
        ingresar_servicio.setBackground(Color.darkGray);
    }//GEN-LAST:event_ingresar_servicioMouseExited

    private void ingresar_servicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_servicioMouseEntered
        ingresar_servicio.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_ingresar_servicioMouseEntered

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        actualizar_servicio.setBackground(Color.DARK_GRAY);
        ActualizarServicio as = new ActualizarServicio();
        as.setVisible(true);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void actualizar_servicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizar_servicioMouseClicked
        ActualizarServicio as = new ActualizarServicio();
        as.setVisible(true);
    }//GEN-LAST:event_actualizar_servicioMouseClicked

    private void actualizar_servicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizar_servicioMouseExited
        actualizar_servicio.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_actualizar_servicioMouseExited

    private void actualizar_servicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizar_servicioMouseEntered
        actualizar_servicio.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_actualizar_servicioMouseEntered

    private void btn_serviciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_serviciosMouseEntered
        btn_servicios.setBackground(new Color(33, 33, 33));
    }//GEN-LAST:event_btn_serviciosMouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        btn_promociones.setBackground(new Color(51, 51, 51));
        panel_promociones.setVisible(false);
        panel_categorias.setVisible(false);
        panel_reservas.setVisible(false);
        panel_usuarios.setVisible(false);
        panel_servicios.setVisible(false);
        panel_registros.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        consultar_promocion.setBackground(Color.DARK_GRAY);
        ConsultarPromocion cp = new ConsultarPromocion();
        cp.setVisible(true);
    }//GEN-LAST:event_jLabel29MouseClicked

    private void consultar_promocionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_promocionMouseClicked
        ConsultarPromocion cp = new ConsultarPromocion();
        cp.setVisible(true);
    }//GEN-LAST:event_consultar_promocionMouseClicked

    private void consultar_promocionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_promocionMouseExited
        consultar_promocion.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_consultar_promocionMouseExited

    private void consultar_promocionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_promocionMouseEntered
        consultar_promocion.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_consultar_promocionMouseEntered

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        ingresar_promocion.setBackground(Color.DARK_GRAY);
        IngresarPromocion ip = new IngresarPromocion();
        ip.setVisible(true);
    }//GEN-LAST:event_jLabel33MouseClicked

    private void ingresar_promocionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_promocionMouseClicked
        IngresarPromocion ip = new IngresarPromocion();
        ip.setVisible(true);
    }//GEN-LAST:event_ingresar_promocionMouseClicked

    private void ingresar_promocionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_promocionMouseExited
        ingresar_promocion.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_ingresar_promocionMouseExited

    private void ingresar_promocionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_promocionMouseEntered
        ingresar_promocion.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_ingresar_promocionMouseEntered

    private void btn_promocionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_promocionesMouseEntered
        btn_promociones.setBackground(new Color(33, 33, 33));
    }//GEN-LAST:event_btn_promocionesMouseEntered

    private void btn_promocionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_promocionesMouseClicked
        panel_categorias.setVisible(false);
        panel_reservas.setVisible(false);
        panel_usuarios.setVisible(false);
        panel_servicios.setVisible(false);
        panel_registros.setVisible(true);
        btn_registros.setBackground(new Color(51, 51, 51));
        btn_reservas.setBackground(new Color(51, 51, 51));
        btn_usuarios.setBackground(new Color(51, 51, 51));
        btn_servicios.setBackground(new Color(51, 51, 51));
        btn_categorias.setBackground(new Color(51, 51, 51));
        panel_promociones.setVisible(true);
    }//GEN-LAST:event_btn_promocionesMouseClicked

    private void btn_serviciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_serviciosMouseClicked
        panel_categorias.setVisible(false);
        panel_reservas.setVisible(false);
        panel_usuarios.setVisible(false);
        panel_promociones.setVisible(false);
        panel_registros.setVisible(true);
        btn_registros.setBackground(new Color(51, 51, 51));
        btn_reservas.setBackground(new Color(51, 51, 51));
        btn_usuarios.setBackground(new Color(51, 51, 51));
        btn_categorias.setBackground(new Color(51, 51, 51));
        btn_promociones.setBackground(new Color(51, 51, 51));
        panel_servicios.setVisible(true);
    }//GEN-LAST:event_btn_serviciosMouseClicked

    private void btn_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMouseClicked
        panel_categorias.setVisible(false);
        panel_reservas.setVisible(false);
        panel_servicios.setVisible(false);
        panel_promociones.setVisible(false);
        panel_registros.setVisible(true);
        btn_registros.setBackground(new Color(51, 51, 51));
        btn_reservas.setBackground(new Color(51, 51, 51));
        btn_categorias.setBackground(new Color(51, 51, 51));
        btn_servicios.setBackground(new Color(51, 51, 51));
        btn_promociones.setBackground(new Color(51, 51, 51));
        panel_usuarios.setVisible(true);
    }//GEN-LAST:event_btn_usuariosMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        btn_reservas.setBackground(new Color(51, 51, 51));
        panel_reservas.setVisible(false);
        panel_categorias.setVisible(false);
        panel_usuarios.setVisible(false);
        panel_servicios.setVisible(false);
        panel_registros.setVisible(false);
        panel_promociones.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        consultar_reserva.setBackground(Color.DARK_GRAY);
        ConsultarReserva consultarReserva = new ConsultarReserva();
        consultarReserva.setVisible(true);
    }//GEN-LAST:event_jLabel35MouseClicked

    private void consultar_reservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_reservaMouseClicked
        ConsultarReserva consultarReserva = new ConsultarReserva();
        consultarReserva.setVisible(true);
    }//GEN-LAST:event_consultar_reservaMouseClicked

    private void consultar_reservaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_reservaMouseExited
        consultar_reserva.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_consultar_reservaMouseExited

    private void consultar_reservaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_reservaMouseEntered
        consultar_reserva.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_consultar_reservaMouseEntered

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        cancelar_reserva.setBackground(Color.DARK_GRAY);
        CancelarReserva cancelarReserva = new CancelarReserva();
        cancelarReserva.setVisible(true);
    }//GEN-LAST:event_jLabel37MouseClicked

    private void cancelar_reservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelar_reservaMouseClicked
        CancelarReserva cancelarReserva = new CancelarReserva();
        cancelarReserva.setVisible(true);
    }//GEN-LAST:event_cancelar_reservaMouseClicked

    private void cancelar_reservaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelar_reservaMouseExited
        cancelar_reserva.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_cancelar_reservaMouseExited

    private void cancelar_reservaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelar_reservaMouseEntered
        cancelar_reserva.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_cancelar_reservaMouseEntered

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        actualizar_estado.setBackground(Color.DARK_GRAY);
        ActualizarEstado actualizarEstado = new ActualizarEstado();
        actualizarEstado.setVisible(true);
    }//GEN-LAST:event_jLabel38MouseClicked

    private void actualizar_estadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizar_estadoMouseClicked
        ActualizarEstado actualizarEstado = new ActualizarEstado();
        actualizarEstado.setVisible(true);
    }//GEN-LAST:event_actualizar_estadoMouseClicked

    private void actualizar_estadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizar_estadoMouseExited
        actualizar_estado.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_actualizar_estadoMouseExited

    private void actualizar_estadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizar_estadoMouseEntered
        actualizar_estado.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_actualizar_estadoMouseEntered

    private void btn_reservasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reservasMouseEntered
        btn_reservas.setBackground(new Color(33, 33, 33));
    }//GEN-LAST:event_btn_reservasMouseEntered

    private void btn_reservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reservasMouseClicked
        panel_categorias.setVisible(false);
        panel_usuarios.setVisible(false);
        panel_servicios.setVisible(false);
        panel_promociones.setVisible(false);
        panel_registros.setVisible(true);
        btn_registros.setBackground(new Color(51, 51, 51));
        btn_categorias.setBackground(new Color(51, 51, 51));
        btn_usuarios.setBackground(new Color(51, 51, 51));
        btn_servicios.setBackground(new Color(51, 51, 51));
        btn_promociones.setBackground(new Color(51, 51, 51));
        panel_reservas.setVisible(true);
    }//GEN-LAST:event_btn_reservasMouseClicked

    private void consultar_proveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_proveedorMouseEntered
        consultar_proveedor.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_consultar_proveedorMouseEntered

    private void consultar_proveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_proveedorMouseExited
        consultar_proveedor.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_consultar_proveedorMouseExited

    private void consultar_proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_proveedorMouseClicked
        ConsultarProveedor cp = new ConsultarProveedor();
        cp.setVisible(true);
    }//GEN-LAST:event_consultar_proveedorMouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        consultar_proveedor.setBackground(Color.DARK_GRAY);
        ConsultarProveedor cp = new ConsultarProveedor();
        cp.setVisible(true);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void consultar_clienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_clienteMouseEntered
        consultar_cliente.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_consultar_clienteMouseEntered

    private void consultar_clienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_clienteMouseExited
        consultar_cliente.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_consultar_clienteMouseExited

    private void consultar_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_clienteMouseClicked
        ConsultarCliente cc = new ConsultarCliente();
        cc.setVisible(true);
    }//GEN-LAST:event_consultar_clienteMouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        consultar_cliente.setBackground(Color.DARK_GRAY);
        ConsultarCliente cc = new ConsultarCliente();
        cc.setVisible(true);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        btn_categorias.setBackground(new Color(51, 51, 51));
        panel_categorias.setVisible(false);

        panel_reservas.setVisible(false);
        panel_usuarios.setVisible(false);
        panel_servicios.setVisible(false);
        panel_registros.setVisible(false);
        panel_promociones.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        ingresar_categoria.setBackground(Color.DARK_GRAY);
        IngresarCategoria ic = new IngresarCategoria();
        ic.setVisible(true);
    }//GEN-LAST:event_jLabel40MouseClicked

    private void ingresar_categoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_categoriaMouseClicked
        IngresarCategoria ic = new IngresarCategoria();
        ic.setVisible(true);
    }//GEN-LAST:event_ingresar_categoriaMouseClicked

    private void ingresar_categoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_categoriaMouseExited
        ingresar_categoria.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_ingresar_categoriaMouseExited

    private void ingresar_categoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_categoriaMouseEntered
        ingresar_categoria.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_ingresar_categoriaMouseEntered

    private void btn_categoriasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categoriasMouseEntered
        btn_categorias.setBackground(new Color(33, 33, 33));
    }//GEN-LAST:event_btn_categoriasMouseEntered

    private void btn_categoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categoriasMouseClicked
        panel_registros.setVisible(false);
        
        panel_reservas.setVisible(false);
        panel_usuarios.setVisible(false);
        panel_servicios.setVisible(false);
        btn_registros.setBackground(new Color(51, 51, 51));
        btn_reservas.setBackground(new Color(51, 51, 51));
        btn_usuarios.setBackground(new Color(51, 51, 51));
        btn_servicios.setBackground(new Color(51, 51, 51));
        btn_promociones.setBackground(new Color(51, 51, 51));
        panel_categorias.setVisible(true);
    }//GEN-LAST:event_btn_categoriasMouseClicked

    private void btn_categoriasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categoriasMouseExited
        if (!panel_categorias.isVisible()) {
            btn_categorias.setBackground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_btn_categoriasMouseExited

    private void btn_reservasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reservasMouseExited
        if (!panel_reservas.isVisible()) {
            btn_reservas.setBackground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_btn_reservasMouseExited

    private void btn_usuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMouseExited
        if (!panel_usuarios.isVisible()) {
            btn_usuarios.setBackground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_btn_usuariosMouseExited

    private void btn_serviciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_serviciosMouseExited
        if (!panel_servicios.isVisible()) {
            btn_servicios.setBackground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_btn_serviciosMouseExited

    private void btn_promocionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_promocionesMouseExited
        if (!panel_promociones.isVisible()) {
            btn_promociones.setBackground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_btn_promocionesMouseExited

    private void jLabel40MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseEntered
        ingresar_categoria.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabel40MouseEntered

    private void jLabel37MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseEntered
        cancelar_reserva.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabel37MouseEntered

    private void jLabel38MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseEntered
        actualizar_estado.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabel38MouseEntered

    private void jLabel35MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseEntered
        consultar_reserva.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabel35MouseEntered

    private void jLabel28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseEntered
        consultar_proveedor.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabel28MouseEntered

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        ingresar_usuario.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabel20MouseEntered

    private void jLabel23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseEntered
        consultar_cliente.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabel23MouseEntered

    private void jLabel27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseEntered
        actualizar_servicio.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabel27MouseEntered

    private void jLabel26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseEntered
        ingresar_servicio.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabel26MouseEntered

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        consultar_servicio.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jLabel33MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseEntered
        ingresar_promocion.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabel33MouseEntered

    private void jLabel29MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseEntered
        consultar_promocion.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabel29MouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

    }//GEN-LAST:event_jLabel1MouseClicked

    private void btn_promociones1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_promociones1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_promociones1MouseClicked

    private void btn_promociones1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_promociones1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_promociones1MouseEntered

    private void btn_promociones1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_promociones1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_promociones1MouseExited

    private void btn_registrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrosMouseClicked
        panel_categorias.setVisible(false);
        panel_reservas.setVisible(false);
        panel_usuarios.setVisible(false);
        panel_servicios.setVisible(false);
        btn_reservas.setBackground(new Color(51, 51, 51));
        btn_usuarios.setBackground(new Color(51, 51, 51));
        btn_servicios.setBackground(new Color(51, 51, 51));
        btn_categorias.setBackground(new Color(51, 51, 51));
        panel_promociones.setVisible(false);
        panel_registros.setVisible(true);
    }//GEN-LAST:event_btn_registrosMouseClicked

    private void btn_registrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrosMouseEntered
        btn_registros.setBackground(new Color(33, 33, 33));
    }//GEN-LAST:event_btn_registrosMouseEntered

    private void btn_registrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrosMouseExited
        if (!panel_registros.isVisible()) {
            btn_registros.setBackground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_btn_registrosMouseExited

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        btn_registros.setBackground(new Color(51, 51, 51));
        panel_registros.setVisible(false);
        panel_categorias.setVisible(false);
        panel_reservas.setVisible(false);
        panel_usuarios.setVisible(false);
        panel_servicios.setVisible(false);

        panel_promociones.setVisible(false);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
        ConsultarRegistro consultarRegistro = new ConsultarRegistro();
        consultarRegistro.setVisible(true);
    }//GEN-LAST:event_jLabel42MouseClicked

    private void jLabel42MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseEntered
        consultar_registros.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabel42MouseEntered

    private void consultar_serviciosMasVisitadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_serviciosMasVisitadosMouseClicked
        consultarServiciosMasVisitados consultarRegistro = new consultarServiciosMasVisitados();
        consultarRegistro.setVisible(true);
    }//GEN-LAST:event_consultar_serviciosMasVisitadosMouseClicked

    private void consultar_serviciosMasVisitadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_serviciosMasVisitadosMouseEntered
        consultar_serviciosMasVisitados.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_consultar_serviciosMasVisitadosMouseEntered

    private void consultar_serviciosMasVisitadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_serviciosMasVisitadosMouseExited
        consultar_serviciosMasVisitados.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_consultar_serviciosMasVisitadosMouseExited

    private void consultar_registrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_registrosMouseClicked
        ConsultarRegistro consultarRegistro = new ConsultarRegistro();
        consultarRegistro.setVisible(true);
    }//GEN-LAST:event_consultar_registrosMouseClicked

    private void consultar_registrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_registrosMouseEntered
        consultar_registros.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_consultar_registrosMouseEntered

    private void consultar_registrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_registrosMouseExited
        consultar_registros.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_consultar_registrosMouseExited

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel45MouseClicked

    private void jLabel45MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseEntered
        consultar_serviciosMasVisitados.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabel45MouseEntered

    private void jLabel44MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseEntered
        consultar_registros.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabel44MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actualizar_estado;
    private javax.swing.JPanel actualizar_servicio;
    private javax.swing.JLabel btn_categorias;
    private javax.swing.JLabel btn_promociones;
    private javax.swing.JLabel btn_promociones1;
    private javax.swing.JLabel btn_registros;
    private javax.swing.JLabel btn_reservas;
    private javax.swing.JLabel btn_servicios;
    private javax.swing.JLabel btn_usuarios;
    private javax.swing.JPanel cancelar_reserva;
    private javax.swing.JPanel consultar_cliente;
    private javax.swing.JPanel consultar_promocion;
    private javax.swing.JPanel consultar_proveedor;
    private javax.swing.JPanel consultar_registros;
    private javax.swing.JPanel consultar_reserva;
    private javax.swing.JPanel consultar_servicio;
    private javax.swing.JPanel consultar_serviciosMasVisitados;
    private javax.swing.JPanel ingresar_categoria;
    private javax.swing.JPanel ingresar_promocion;
    private javax.swing.JPanel ingresar_servicio;
    private javax.swing.JPanel ingresar_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_menu;
    private javax.swing.JLabel lbl_mostrar_registros1;
    private javax.swing.JPanel panel_categorias;
    private javax.swing.JPanel panel_promociones;
    private javax.swing.JPanel panel_registros;
    private javax.swing.JPanel panel_reservas;
    private javax.swing.JPanel panel_servicios;
    private javax.swing.JPanel panel_usuarios;
    // End of variables declaration//GEN-END:variables
}
